#!/usr/bin/env bash
# Install nginx on your web-01 server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

ufw allow 'Nginx HTTP'

# Get the hostname of the server
HOSTNAME=$(hostname)

# Define the Nginx configuration file path
NGINX_CONF_PATH="/etc/nginx/sites-available/default"

sudo chown -R $USER:$USER /etc/nginx
sudo chown -R $USER:$USER /var/www


STRING="Hello World!"

REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 http://dev-israel.tech;\n\t}\n"
FILE="/etc/nginx/sites-available/default"

ERRORFILE="/usr/share/nginx/html/404error.html"
FOUR="Ceci n'est pas une page"
ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\tadd_header X-Served-Bsdfsfy $HOSTNAME;\n\t}\n"

# DEFAULTFILE="/usr/share/nginx/html/404error.html"V    
# DEFAULT_CONFIG="\n\tlocation / {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\tadd_header X-Served-By $HOSTNAME;\n\t}\n"

echo "$STRING" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $REDIRECT" "$FILE"

sudo chown -R $USER:$USER "/usr/share/nginx/html"
echo "$FOUR" > "$ERRORFILE"
sed -i "37i\ $ERRORREDIRECT" "$FILE"

sudo sed -i "/location \/ {\n\t\t/a $custom_header\n\t" "$FILE"

# Reload Nginx to apply the changes
sudo service nginx restart
